import Head from "next/head";
import Image from "next/image";
import Layout from "~/components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 gap-6 p-4 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3">
            <div className="flex h-96 w-full flex-col items-center justify-center overflow-hidden rounded-lg shadow-lg">
              <div className="border-logotipOrange relative h-full w-full border-b-2">
                <Image
                  className="h-auto w-full object-cover object-center"
                  src="/assets/canvas.jpg"
                  alt="photo"
                  fill
                ></Image>
              </div>
              <div className="py-8 text-center sm:py-6">
                <p className="mb-1 text-2xl font-bold text-white">
                  Tablouri Canvas
                </p>
              </div>
            </div>
            <div className="flex h-96 w-full flex-col items-center justify-center overflow-hidden rounded-lg shadow-lg">
              <div className="border-logotipOrange relative h-full w-full border-b-2">
                <Image
                  className="h-auto w-full object-cover object-center"
                  src="/assets/cana.webp"
                  alt="photo"
                  fill
                ></Image>
              </div>
              <div className="py-8 text-center sm:py-6">
                <p className="mb-1 text-2xl font-bold text-white">
                  Cani Personalizate
                </p>
              </div>
            </div>
            <div className="flex h-96 w-full flex-col items-center justify-center overflow-hidden rounded-lg shadow-lg">
              <div className="border-logotipOrange relative h-full w-full border-b-2">
                <Image
                  className="h-auto w-full object-cover object-center"
                  src="/assets/tricouri.webp"
                  alt="photo"
                  fill
                ></Image>
              </div>
              <div className="py-8 text-center sm:py-6">
                <p className="mb-1 text-2xl font-bold text-white">
                  Tricouri Personalizate
                </p>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
