const produse = [
  {
    id: 1,
    name: "Tricouri Personalizate",
    image: "",
    link: "tricouri-personalizate",
    subcategories: [
      {
        id: 1,
        name: "Pentru Aniversari",
        image: "",
        link: "aniversari",
        designs: [
          {
            id: 1,
            name: "Aniversare 1 an",
            image: "",
            link: "aniversare-1-an",
          },
        ],
      },
      {
        id: 2,
        name: "Pentru Cupluri",
        image: "",
        link: "cupluri",
        designs: [],
      },
      {
        id: 3,
        name: "Pentru Mamici si Tatici in devenire",
        image: "",
        link: "mamici-tatici-in-devenire",
        designs: [],
      },
      {
        id: 4,
        name: "Cu mesaje amuzante",
        image: "",
        link: "mesaje-amuzante",
        designs: [],
      },
      {
        id: 5,
        name: "Pentru copii",
        image: "",
        link: "copii",
        designs: [],
      },
      {
        id: 6,
        name: "Pentru Burlacite",
        image: "",
        link: "burlacite",
        designs: [],
      },
      {
        id: 7,
        name: "Pentru Burlaci",
        image: "",
        link: "burlaci",
        designs: [],
      },
    ],
  },
  {
    id: 2,
    name: "Cani/Sticle/Thermos",
    image: "",
    link: "cani-sticle-thermos",
    subcategories: [
      {
        id: 1,
        name: "Albe si Colorate",
        image: "",
        link: "cani-albe-si-colorate",
        designs: [],
      },
      {
        id: 2,
        name: "Cu toarta in forma de inima",
        image: "",
        link: "toarta-in-forma-de-inima",
        designs: [],
      },
      {
        id: 3,
        name: "Pentru Cafea",
        image: "",
        link: "cafea",
        designs: [],
      },
      {
        id: 4,
        name: "Termosensibile",
        image: "",
        link: "termosensibile",
        designs: [],
      },
      {
        id: 5,
        name: "Pentru Copii",
        image: "",
        link: "copii",
        designs: [],
      },
      {
        id: 6,
        name: "Emailate",
        image: "",
        link: "emailate",
        designs: [],
      },
      {
        id: 7,
        name: "Halbe de bere",
        image: "",
        link: "halbe-de-bere",
        designs: [],
      },
    ],
  },
  {
    id: 3,
    name: "Personalizari Diverse",
    image: "",
    link: "personalizari-diverse",
    subcategories: [
      {
        id: 1,
        name: "Sorturi Personalizate",
        image: "",
        link: "sorturi-personalizate",
        designs: [],
      },
      {
        id: 2,
        name: "Sucitor de lemn personalizat",
        image: "",
        link: "sucitor-de-lemn-personalizat",
        designs: [],
      },
      {
        id: 3,
        name: "Tocatoare de lemn personalizate",
        image: "",
        link: "tocatoare-de-lemn-personalizate",
        designs: [],
      },
      {
        id: 4,
        name: "Cutii si Sacose de vin",
        image: "",
        link: "cutii-si-sacose-de-vin",
        designs: [],
      },
      {
        id: 5,
        name: "Sticle de vin personalizate",
        image: "",
        link: "sticle-de-vin-personalizate",
        designs: [],
      },
      {
        id: 6,
        name: "Perne personalizate",
        image: "",
        link: "perne-personalizate",
        designs: [],
      },
      {
        id: 7,
        name: "Saculeti si Rucsacuri",
        image: "",
        link: "saculeti-si-rucsacuri",
        designs: [],
      },
      {
        id: 8,
        name: "Mouse pad-uri",
        image: "",
        link: "mouse-pad-uri",
        designs: [],
      },
      {
        id: 9,
        name: "Puzzle-uri",
        image: "",
        link: "puzzle-uri",
        designs: [],
      },
      {
        id: 10,
        name: "Rame Ardezie",
        image: "",
        link: "rame-ardezie",
        designs: [],
      },
      {
        id: 11,
        name: "Ceasuri de perete",
        image: "",
        link: "ceasuri-de-perete",
        designs: [],
      },
    ],
  },
  {
    id: 4,
    name: "Ocazii/Evenimente",
    image: "",
    link: "ocazii-si-evenimente",
    subcategories: [
      {
        id: 1,
        name: "Cadouri pentru aniversare",
        image: "",
        link: "aniversare",
        designs: [],
      },
      {
        id: 2,
        name: "Cadouri pentru 1 si 8 Martie",
        image: "",
        link: "1-8-martie",
        designs: [],
      },
      {
        id: 3,
        name: "Cadouri de Craciun",
        image: "",
        link: "craciun",
        designs: [],
      },
      {
        id: 4,
        name: "Cadouri pentru ?",
        image: "",
        link: "cadouri-pentru",
        designs: [],
      },
      {
        id: 5,
        name: "Cadouri pentru botez",
        image: "",
        link: "cadouri-botez",
        designs: [],
      },
      {
        id: 6,
        name: "Cadouri pentru nunta si cununie",
        image: "",
        link: "cadouri-nunta-cununie",
        designs: [],
      },
      {
        id: 7,
        name: "Cadouri pentru aniversare relatie/casnicie",
        image: "",
        link: "cadouri-aniversare-relatie-casnicie",
        designs: [],
      },
      {
        id: 8,
        name: "Cadouri pentru pensionare",
        image: "",
        link: "cadouri-pensionare",
        designs: [],
      },
      {
        id: 9,
        name: "Cadouri pentru apreciere",
        image: "",
        link: "cadouri-apreciere",
        designs: [],
      },
    ],
  },
  {
    id: 5,
    name: "Destinatari",
    image: "",
    link: "destinatari",
    subcategories: [
      {
        id: 1,
        name: "Cadouri pentru parinti si nasi",
        image: "",
        link: "cadouri-parinti-nasi",
        designs: [],
      },
      {
        id: 2,
        name: "Cadouri pentru bunici",
        image: "",
        link: "cadouri-bunici",
        designs: [],
      },
      {
        id: 3,
        name: "Cadouri pentru profesori",
        image: "",
        link: "cadouri-profesori",
        designs: [],
      },
      {
        id: 4,
        name: "Cadouri pentru nou-nascuti",
        image: "",
        link: "cadouri-nou-nascuti",
        designs: [],
      },
      {
        id: 5,
        name: "Cadouri pentru iubit/iubita",
        image: "",
        link: "cadouri-iubit-iubita",
        designs: [],
      },
      {
        id: 5,
        name: "Cadouri pentru copii",
        image: "",
        link: "cadouri-copii",
        designs: [],
      },
    ],
  },
  {
    id: 6,
    name: "Copii",
    image: "",
    link: "copii",
    subcategories: [],
  },
];

export default produse;
