const produse = [
  {
    id: 1,
    name: "Tricouri Personalizate",
    image: "",
    link: "/tricouri-personalizate",
    subcategories: [
      {
        id: 1,
        name: "Pentru Aniversari",
        image: "",
        link: "/aniversari",
      },
      {
        id: 2,
        name: "Pentru Cupluri",
        image: "",
        link: "/cupluri",
      },
      {
        id: 3,
        name: "Pentru Mamici si Tatici in devenire",
        image: "",
        link: "/mamici-tatici-in-devenire",
      },
      {
        id: 4,
        name: "Cu mesaje amuzante",
        image: "",
        link: "/mesaje-amuzante",
      },
      {
        id: 5,
        name: "Pentru copii",
        image: "",
        link: "/copii",
      },
      {
        id: 6,
        name: "Pentru Burlacite",
        image: "",
        link: "/burlacite",
      },
      {
        id: 7,
        name: "Pentru Burlaci",
        image: "",
        link: "/burlaci",
      },
    ],
  },
  {
    id: 2,
    name: "Cani/Sticle/Thermos",
    image: "",
    link: "/cani-sticle-thermos",
    subcategories: [
      {
        id: 1,
        name: "Albe si Colorate",
        image: "",
        link: "/cani-albe-si-colorate",
      },
      {
        id: 2,
        name: "Cu toarta in forma de inima",
        image: "",
        link: "/toarta-in-forma-de-inima",
      },
      {
        id: 3,
        name: "Pentru Cafea",
        image: "",
        link: "/cafea",
      },
      {
        id: 4,
        name: "Termosensibile",
        image: "",
        link: "/termosensibile",
      },
      {
        id: 5,
        name: "Pentru Copii",
        image: "",
        link: "/copii",
      },
      {
        id: 6,
        name: "Emailate",
        image: "",
        link: "/emailate",
      },
      {
        id: 7,
        name: "Halbe de bere",
        image: "",
        link: "/halbe-de-bere",
      },
    ],
  },
  {
    id: 3,
    name: "Personalizari Diverse",
    image: "",
    link: "/personalizari-diverse",
    subcategories: [
      {
        id: 1,
        name: "Sorturi Personalizate",
        image: "",
        link: "/sorturi-personalizate",
      },
      {
        id: 2,
        name: "Sucitor de lemn personalizat",
        image: "",
        link: "/sucitor-de-lemn-personalizat",
      },
      {
        id: 3,
        name: "Tocatoare de lemn personalizate",
        image: "",
        link: "/tocatoare-de-lemn-personalizate",
      },
      {
        id: 4,
        name: "Cutii si Sacose de vin",
        image: "",
        link: "/cutii-si-sacose-de-vin",
      },
      {
        id: 5,
        name: "Sticle de vin personalizate",
        image: "",
        link: "/sticle-de-vin-personalizate",
      },
      {
        id: 6,
        name: "Perne personalizate",
        image: "",
        link: "/perne-personalizate",
      },
      {
        id: 7,
        name: "Saculeti si Rucsacuri",
        image: "",
        link: "/saculeti-si-rucsacuri",
      },
      {
        id: 8,
        name: "Mouse pad-uri",
        image: "",
        link: "/mouse-pad-uri",
      },
      {
        id: 9,
        name: "Puzzle-uri",
        image: "",
        link: "/puzzle-uri",
      },
      {
        id: 10,
        name: "Rame Ardezie",
        image: "",
        link: "/rame-ardezie",
      },
      {
        id: 11,
        name: "Ceasuri de perete",
        image: "",
        link: "/ceasuri-de-perete",
      },
    ],
  },
  {
    id: 4,
    name: "Ocazii/Evenimente",
    image: "",
    link: "/ocazii-si-evenimente",
    subcategories: [
      {
        id: 1,
        name: "Cadouri pentru aniversare",
        image: "",
        link: "/aniversare",
      },
      {
        id: 2,
        name: "Cadouri pentru 1 si 8 Martie",
        image: "",
        link: "/1-8-martie",
      },
      {
        id: 3,
        name: "Cadouri de Craciun",
        image: "",
        link: "/craciun",
      },
      {
        id: 4,
        name: "Cadouri pentru ?",
        image: "",
        link: "/cadouri-pentru",
      },
      {
        id: 5,
        name: "Cadouri pentru botez",
        image: "",
        link: "/cadouri-botez",
      },
      {
        id: 6,
        name: "Cadouri pentru nunta si cununie",
        image: "",
        link: "/cadouri-nunta-cununie",
      },
      {
        id: 7,
        name: "Cadouri pentru aniversare relatie/casnicie",
        image: "",
        link: "/cadouri-aniversare-relatie-casnicie",
      },
      {
        id: 8,
        name: "Cadouri pentru pensionare",
        image: "",
        link: "/cadouri-pensionare",
      },
      {
        id: 9,
        name: "Cadouri pentru apreciere",
        image: "",
        link: "/cadouri-apreciere",
      },
    ],
  },
  {
    id: 5,
    name: "Destinatari",
    image: "",
    link: "/destinatari",
    subcategories: [
      {
        id: 1,
        name: "Cadouri pentru parinti si nasi",
        image: "",
        link: "/cadouri-parinti-nasi",
      },
      {
        id: 2,
        name: "Cadouri pentru bunici",
        image: "",
        link: "/cadouri-bunici",
      },
      {
        id: 3,
        name: "Cadouri pentru profesori",
        image: "",
        link: "/cadouri-profesori",
      },
      {
        id: 4,
        name: "Cadouri pentru nou-nascuti",
        image: "",
        link: "/cadouri-nou-nascuti",
      },
      {
        id: 5,
        name: "Cadouri pentru iubit/iubita",
        image: "",
        link: "/cadouri-iubit-iubita",
      },
      {
        id: 5,
        name: "Cadouri pentru copii",
        image: "",
        link: "/cadouri-copii",
      },
    ],
  },
  {
    id: 6,
    name: "Copii",
    image: "",
    link: "/copii",
    subcategories: [],
  },
];

export default produse;
